entities:
  - name: carrot1
    prefab_name: carrot
    pose:
      translation:
        x: 0.3
        y: -0.45
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: apple1
    prefab_name: apple
    pose:
      translation:
        x: 0.3
        y: -0.10
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: tomato1
    prefab_name: tomato
    pose:
      translation:
        x: 0.3
        y: -0.10
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: tomato2
    prefab_name: tomato
    pose:
      translation:
        x: 0.3
        y: -0.15
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: blue_cube1
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.40
        y: 0.40
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: red_cube1
    prefab_name: red_cube
    pose:
      translation:
        x: 0.45
        y: 0.40
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: yellow_cube1
    prefab_name: yellow_cube
    pose:
      translation:
        x: 0.50
        y: 0.40
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: yellow_cube2
    prefab_name: yellow_cube
    pose:
      translation:
        x: 0.50
        y: 0.40
        z: 0.15
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: yellow_cube3
    prefab_name: yellow_cube
    pose:
      translation:
        x: 0.50
        y: 0.40
        z: 0.25
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
