entities:
  - name: apple1
    prefab_name: apple
    pose:
      translation:
        x: 0.4
        y: -0.3
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: apple2
    prefab_name: apple
    pose:
      translation:
        x: 0.3
        y: -0.2
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: apple3
    prefab_name: apple
    pose:
      translation:
        x: 0.5
        y: 0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: corn1
    prefab_name: corn
    pose:
      translation:
        x: 0.4
        y: -0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.707
        z: 0.0
        w: 0.707
  - name: corn2
    prefab_name: corn
    pose:
      translation:
        x: 0.4
        y: 0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.707
        z: 0.0
        w: 0.707
  - name: corn3
    prefab_name: corn
    pose:
      translation:
        x: 0.3
        y: -0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.707
        z: 0.0
        w: 0.707
  - name: corn4
    prefab_name: corn
    pose:
      translation:
        x: 0.5
        y: 0.3
        z: 0.05
      rotation:
        x: 0.0
        y: 0.707
        z: 0.0
        w: 0.707
  - name: blue_cube1
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.5
        y: -0.1
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: blue_cube2
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.35
        y: 0.2
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
