entities:
  - name: red_cube1
    prefab_name: red_cube
    pose:
      translation:
        x: 0.50
        y: 0.00
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: red_cube2
    prefab_name: red_cube
    pose:
      translation:
        x: 0.45
        y: 0.35
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: red_cube3
    prefab_name: red_cube
    pose:
      translation:
        x: 0.35
        y: -0.45
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: apple1
    prefab_name: apple
    pose:
      translation:
        x: 0.35
        y: -0.10
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: apple2
    prefab_name: apple
    pose:
      translation:
        x: 0.30
        y: 0.20
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: carrot1
    prefab_name: carrot
    pose:
      translation:
        x: 0.45
        y: -0.20
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
